// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxUFk7mmhFFsREbyHAL2zAdcnRPNxIEiE',
    appId: '1:53963137436:web:047185ee6c636719dfa859',
    messagingSenderId: '53963137436',
    projectId: 'lawmaster-a0a6c',
    authDomain: 'lawmaster-a0a6c.firebaseapp.com',
    databaseURL: 'https://lawmaster-a0a6c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lawmaster-a0a6c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj8b3ZirPf1r5LW1R3J_1ADtzZpgqj8F8',
    appId: '1:53963137436:android:4b5a900040f9da82dfa859',
    messagingSenderId: '53963137436',
    projectId: 'lawmaster-a0a6c',
    databaseURL: 'https://lawmaster-a0a6c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lawmaster-a0a6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCprRT1uR_JnVTkSs4_02_uGjj_JfXGsDg',
    appId: '1:53963137436:ios:c987643301ae812cdfa859',
    messagingSenderId: '53963137436',
    projectId: 'lawmaster-a0a6c',
    databaseURL: 'https://lawmaster-a0a6c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lawmaster-a0a6c.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCprRT1uR_JnVTkSs4_02_uGjj_JfXGsDg',
    appId: '1:53963137436:ios:c987643301ae812cdfa859',
    messagingSenderId: '53963137436',
    projectId: 'lawmaster-a0a6c',
    databaseURL: 'https://lawmaster-a0a6c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lawmaster-a0a6c.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxUFk7mmhFFsREbyHAL2zAdcnRPNxIEiE',
    appId: '1:53963137436:web:5c786c7e76d46725dfa859',
    messagingSenderId: '53963137436',
    projectId: 'lawmaster-a0a6c',
    authDomain: 'lawmaster-a0a6c.firebaseapp.com',
    databaseURL: 'https://lawmaster-a0a6c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lawmaster-a0a6c.firebasestorage.app',
  );
}
